[package]
name = "strace"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

[dependencies]
bitflags = "1.1.0"
structopt = { version = "0.2.18", optional = true }
redox_syscall = "0.2"

[features]
default = [ "advanced" ]
advanced = [ "structopt" ]
trace = []
